[enrich] Get main enrollment for *_org_name field
chaoss/grimoirelab-elk pull request #1018
Opened 2021-12-22 18:10 UTC by zhquan

This code gets the main enrollment for `*_org_name` when
there are several enrollments.

If the enrollment contains :: the main one is the first part.

For example:
- Enrollment: Chaoss::Eng
- Main: Chaoss

If there is more than one, it will return the first one ordered
alphabetically.

Test added accordingly.

Signed-off-by: Quan Zhou <quan@bitergia.com>

2021-12-23 11:13 UTC, sduenas requested changes
Looks ok but we can improve it a bit using python functions.

2021-12-23 11:13 UTC, sduenas commented on grimoire_elk/enriched/enrich.py
> +        all_enrolls = multi_enrolls + list(set(main_enrolls) - set(multi_enrolls))
I don't get this. Shouldn't it be only:

```
list(set(main_enrolls) + set(multi_enrolls))
```
???

2021-12-23 12:09 UTC, zhquan commented on grimoire_elk/enriched/enrich.py
> +        all_enrolls = multi_enrolls + list(set(main_enrolls) - set(multi_enrolls))
```
all_enrolls = multi_enrolls + list(set(main_enrolls) - set(multi_enrolls))
````
We have:
- multi_enrolls = ["Bitergia::Eng", "Chaoss", "Bitergia"]
- main_enrolls = ["Bitergia", "Chaoss"]

We need to get the unique values between these two lists:
`all multi_enrolls` + all in `main_enrolls` but not in `multi_enrolls`
- all_enrolls = ['Bitergia::Eng', 'Chaoss', 'Bitergia']

2021-12-23 12:45 UTC, sduenas commented on grimoire_elk/enriched/enrich.py
> +        all_enrolls = multi_enrolls + list(set(main_enrolls) - set(multi_enrolls))
Yes, but if you have those into sets and you add both sets, you'll have the result you mention there.

2021-12-27 12:25 UTC, sduenas approved these changes
LGTM

2021-12-27 15:14 UTC, merged