[gha] Create release.yml file
chaoss/grimoirelab-elk pull request #1030
Opened 2022-02-02 11:02 UTC by jjmerchante

This commit adds a new GitHub Action to create the release for ELK. It generates a package, tests it, and publishes the release on PyPi and GitHub whenever a tag is generated and pushed.

It also updates `statsmodels` package in Poetry to 0.12.0 (maximum available version of statsmodels for Python 3.6) and updates poetry.lock.

2022-03-23 09:29 UTC, vchrombie requested changes
Thanks for opening the PR @jjmerchante 
This PR has a few conflicts, can you fix them and mark the PR as ready for review?

2022-04-01 07:09 UTC, vchrombie commented
@jjmerchante we just have this PR left in the task list. It would be great if you can update the PR when you get some free time.
Thank you.

2022-04-04 07:50 UTC, vchrombie reviewed
Very small change needed before we merge it, just to make the workflows consistent.

2022-04-04 07:50 UTC, vchrombie commented on .github/workflows/release.yml
> +      - name: "Build package using Poetry and store result."
small nit, can you remove the quotes from the `name`

2022-04-05 14:44 UTC, sduenas approved these changes
LGTM, @vchrombie what do you think?

2022-04-06 07:09 UTC, vchrombie approved these changes
LGTM!

2022-04-06 07:10 UTC, vchrombie commented
Thanks for the PR @jjmerchante.

2022-04-06 08:38 UTC, merged