Set SortingHat as a required package in grimoireelk
chaoss/grimoirelab-elk pull request #1050
Opened 2022-05-13 09:42 UTC by jjmerchante

SortingHat was set as an extra dependency in elk, but actually it is required for running elk.

This PR updates the Poetry dependencies to make it a required package and updates the GitHub actions to remove Sortinghat as an extra dependency.

2022-05-19 16:59 UTC, sduenas commented
Related to: https://github.com/chaoss/grimoirelab/issues/489

2022-05-19 17:01 UTC, sduenas requested changes
LGTM but you should update the dependencies. They were updated in the last PR we merged. Thanks!

2022-05-20 06:55 UTC, jjmerchante commented
PR rebased and dependencies updated

2022-05-20 08:22 UTC, sduenas commented on releases/unreleased/set-sortinghat-as-a-required-package-in-elk.yml
> +title: Set SortingHat as a required package in elk
I think this title is better for the changelog.

```suggestion
title: SortingHat as a required package
```

2022-05-20 08:22 UTC, sduenas requested changes
LGTM but check my comment if it makes sense to you.

2022-05-20 09:00 UTC, sduenas approved these changes
LGTM

2022-05-20 09:02 UTC, merged