Collect and enrich confluence by spaces
chaoss/grimoirelab-elk pull request #1051
Opened 2022-05-13 15:14 UTC by zhquan

This code allows to collect and enrich confluence by spaces
adding `--spaces=[SPACE1, SPACE2]` on the projects.json.

For instance, the following projecs.json it will collect and
enrich the space `DEV` for the `Main` project and `SUPP`
space for `Support` project.

```
{
    "Main": {
        "confluence": [
            "https://example.com --spaces=[DEV]"
        ]
    },
    "Support": {
        "confluence": [
            "https://example.com --spaces=[SUPP]"
        ]
    }
}
```

Method updated:
- elastic_items.extract_repo_tags:
    - `tag`: New argument to select labels or spaces
- raw.elastc.get_perceval_params_from_url:
    - Get parameter `spaces` given a URL
- enriched.utils.get_confluence_spaces_filter:
    - Create a query to get items from `spaces`

Test added accordingly.

Signed-off-by: Quan Zhou <quan@bitergia.com>

2022-05-19 10:33 UTC, sduenas requested changes
I think the PR is ok but please check my comments.

2022-05-19 10:33 UTC, sduenas commented on releases/unreleased/collect-and-enrich-confluence-by-spaces.yml
> +    only the `DEV` and `SUPP` spaces.
```suggestion
    Users can collect and enrich Confluence data from specific spaces only,
    adding the option `--spaces=[SPACE1, SPACE2, ...]` to their `projects.json`.

    The following example shows how to collect and to enrich data from
    only the `DEV` and `SUPP` spaces only.
```

2022-05-19 10:33 UTC, sduenas commented on tests/test_elastic_items.py
> +        eitems = MeetupOcean(perceval_backend_meetup)
I think this is a mistake and it should be there.

2022-05-19 10:33 UTC, sduenas commented on tests/test_elastic_items.py
> +        self.assertDictEqual(fltr, expected_filter)
And probably this should go replacing the other previous lines.

2022-05-19 10:33 UTC, sduenas commented on tests/test_elastic_items.py
> +        self.assertListEqual(space_lst, [])
Shouldn't go this in a different test? The name of the test is `test_extract_repo_labels`. Or maybe it makes sense to change the name.

2022-05-19 10:43 UTC, zhquan commented on tests/test_elastic_items.py
> +        self.assertListEqual(space_lst, [])
Correct the name of the tests should be `test_extract_repo_tags`

2022-05-19 10:52 UTC, zhquan commented on tests/test_elastic_items.py
> +        eitems = MeetupOcean(perceval_backend_meetup)
I add Meetup there to check the result when the backend is not Confluence. In the next line I run `eitems.get_confluence_spaces`. I going to change the comment to make it clearer.

2022-05-19 14:53 UTC, sduenas approved these changes
LGTM

2022-05-19 17:03 UTC, sduenas commented
Apparently the commits of this PR were merged in master but the PR wasn't updated.

2022-05-20 08:04 UTC, sduenas commented
Let's close this because the code is already merged.

2022-05-20 08:04 UTC, closed without merging