Use entry points to support plugin mechanism.
chaoss/grimoirelab-elk pull request #1062
Opened 2022-06-16 16:06 UTC by shanchenqi

As we have discussed in  Issue [#496](https://github.com/chaoss/grimoirelab/issues/496), we implemented [grimoirelab-elk-gitee](https://github.com/chaoss/grimoirelab-elk-gitee) as a plugin. In order to support this plugin solution, we need to use entry points as I created in this pull request.

2022-06-21 12:28 UTC, sduenas requested changes
Thanks for your contribution! I've been testing the PR and works fine, however, will you mind to review my comments? Also, you should improve the commit message of this PR. See our [contributing guidelines](https://github.com/chaoss/grimoirelab/blob/master/CONTRIBUTING.md).

2022-06-21 12:28 UTC, sduenas commented on releases/unreleased/Use_entry_points_to_support_plugin_mechanism.yml
> +title: 'Use entry points to support plugin mechanism'
```suggestion
title: Entry points to support enriching plugin mechanism
```

2022-06-21 12:28 UTC, sduenas commented on releases/unreleased/Use_entry_points_to_support_plugin_mechanism.yml
> +notes: The plugin solution is used to incubate a new data source backend solution.
```suggestion
notes: >
    This plugin mechanism allows ELK to use third-party enriching backends.
    Developers only need to include the next snippet in their package configuration
    and ELK will import them as any other core backend. 
    ```
    entry_points={"grimoire_elk": "mybackend = package.subpackage:get_connectors"},
    ```
    **NOTE**: In the previous example, `get_connectors` is a function that returns
    the backend classes needed to enrich a datasource. Take the next snipped
    as an example:
    ```
    def get_connectors():
        return {"backend": [MyBackend, MyBackendOcean, MyBackendEnrich, MyBackendCommand]}
    ```
```

2022-06-21 14:52 UTC, shanchenqi commented
Hi, @sduenas, Thank you for your code review. I have updated my pull request according to your advice.

2022-06-25 11:22 UTC, shanchenqi commented
Excuse me, I force to push the commits again in order to squash the commits into one.

2022-06-30 12:13 UTC, sduenas requested changes
LGTM but, would you mind to change the message of the commit? Follow the guidelines I mentioned before (you can also use part of the text included in the changelog entry). Thanks!

2022-07-02 01:59 UTC, shanchenqi commented
> LGTM but, would you mind to change the message of the commit? Follow the guidelines I mentioned before (you can also use part of the text included in the changelog entry). Thanks!

OK, I got it and updated the code. Thank you~

2022-07-04 09:35 UTC, sduenas approved these changes
LGTM. Thank you so much for your contribution. This feature will improve a lot the core of the platform.

2022-07-04 09:45 UTC, sduenas commented
@shanchenqi last thing, I realized the PR doesn't contain the latest changes of the repo history. Would you mind to rebase it with master before I merge it?

2022-07-06 07:16 UTC, merged

2022-07-06 07:22 UTC, sduenas commented
@shanchenqi thanks for the PR!

2022-07-07 15:47 UTC, shanchenqi commented
> @shanchenqi thanks for the PR!

It's my pleasure!