[enriched/git] Add more git commit meta fields
chaoss/grimoirelab-elk pull request #1087
Opened 2022-10-26 13:13 UTC by zhquan

This code extracts more authors meta info:
- Approved-by
- Co-authored-by
- Merged-by

For each one it will creates 10 new fields.
- suffixes: `_bots`, `_domains`, `_names`, `_org_names`, `_uuids`
- prefix: `non_authored_`

Example of Merged-by:
- merged_by_multi_bots
- merged_by_multi_domains
- merged_by_multi_names
- merged_by_multi_org_names
- merged_by_multi_uuids
- non_authored_merged_by_multi_bots
- non_authored_merged_by_multi_domains
- non_authored_merged_by_multi_names
- non_authored_merged_by_multi_org_names
- non_authored_merged_by_multi_uuids

Signed-off-by: Quan Zhou <quan@bitergia.com>

2022-10-26 13:46 UTC, jjmerchante commented
LGTM

2022-10-26 14:38 UTC, sduenas commented on grimoire_elk/enriched/git.py
> +    meta_fields = ['acked_by_multi', 'approved_by_multi', 'co_authored_by_multi', 'co_developed_by_multi',
Perceval doesn't support this list of trailers. How is it possible the end in the enriched indices?

2022-10-26 14:49 UTC, zhquan commented on grimoire_elk/enriched/git.py
> +    meta_fields = ['acked_by_multi', 'approved_by_multi', 'co_authored_by_multi', 'co_developed_by_multi',
Perceval fetches the entire commit message and elk parses the commit message to find these trailers and create them.

2022-10-27 12:54 UTC, sduenas requested changes
LGTM, would you  mind to update the changelog with my suggestion and rebase this PR?

2022-10-27 12:54 UTC, sduenas commented on releases/unreleased/git-extracts-more-authors-meta-info.yml
> +    - non_authored_merged_by_multi_org_names
```suggestion
notes: >
    New information about the participants during the development and the
    reviewing processes are available in `Git` items. The Git backend extracts
    these data from `Approved-by`, `Co-authored-by`,  and `Merged-by`
    trailers that some commit messages might include. For each one of these
    trailers, new fields will be available with the suffixes: `_bots`, `_domains`,
    `_names`, `_org_names`, and `_uuids`. Also for each one of these suffixes,
    there will be extra fields with the prefix `non_authored_`.
    This is an example of the fields available for the the trailer `Merged-by`:
        - merged_by_multi_bots
        - merged_by_multi_domains
        - merged_by_multi_names
        - merged_by_multi_org_names
        - merged_by_multi_uuids
        - non_authored_merged_by_multi_bots
        - non_authored_merged_by_multi_domains
        - non_authored_merged_by_multi_names
        - non_authored_merged_by_multi_org_names
```

2022-10-27 12:54 UTC, sduenas commented on releases/unreleased/git-extracts-more-authors-meta-info.yml
> +title: Git extracts more authors meta info
```suggestion
title: Development and reviewing contributors fields for Git items
```

2022-10-27 14:11 UTC, sduenas approved these changes
LGTM

2022-10-27 14:11 UTC, merged