Specify exact mappings for date fields in git documents
chaoss/grimoirelab-elk pull request #1099
Opened 2023-01-16 12:14 UTC by Rafaeltheraven

Simple PR, just specifies that `AuthorDate` and `CommitDate` are date fields in ES. This allows us to later do better filtering such as being able to specify `AuthorDate <= {Some Date}`.

2023-01-16 15:07 UTC, sduenas requested changes
Thanks for your patch, would you mind to rebase the PR (cause the tests are failing), and add to the body of the commit message the text "This allows us to later do better filtering such as being able to specify AuthorDate <= {Some Date}.". Thanks!

2023-01-17 10:38 UTC, Rafaeltheraven commented
Amended the commit message and made the tests pass is the rebase good like this? I must admit I am not very familiar with more "proper" advanced git techniques.

2023-01-17 13:45 UTC, sduenas commented
> Amended the commit message and made the tests pass is the rebase good like this? I must admit I am not very familiar with more "proper" advanced git techniques.

You need to run the command `git rebase -i master` on the branch of this PR. The editor will open with a list of commits, for the 2nd o the last one, where it says `pick` replace it by an `s`(squash), and save the file. The editor will show again the messages you wrote for each commit. Remove everything and paste this:

```
Specify exact mappings for data fields in git documents
This allows us to later do better filtering such as
being able to specify AuthorDate <= {Some Date}.
Tests updated accordingly.

The format is compatible with ES6, using `MMM`
instead of `LLL` for the month section.

Signed-off-by: Rafael Dulfer <rafael.dulfer@gmail.com>
```

Save the file and git will squash your commits into a single one and your branch will be updated with the latest commits from master.

2023-01-17 16:05 UTC, Rafaeltheraven commented
Thanks for the guide! Took me a couple of tries, but it's all squashed now

2023-01-18 11:00 UTC, Rafaeltheraven commented
Oh yeah, those got destroyed in my rebasing adventure... After another fun adventure they're merged in now.

2023-01-18 17:57 UTC, sduenas approved these changes
LGTM

2023-01-18 17:57 UTC, merged

2023-01-18 17:58 UTC, sduenas commented
@Rafaeltheraven thanks for your contribution! I successfully merged it. I hope you have learnt some new things with git :)