[ocean] Fix mappings to index DockerHub data
chaoss/grimoirelab-elk pull request #200
Opened 2018-02-12 16:38 UTC by valeriocos

This patch prevents to index the descriptions of docker images, which may cause failures when uploading the data to ES

2018-02-20 10:39 UTC, acs requested changes

2018-02-20 10:39 UTC, acs commented on grimoire_elk/elk/dockerhub.py
> +                    "index": false
We want to index this field. And the same for the two below.

2018-02-22 10:59 UTC, valeriocos commented on grimoire_elk/elk/dockerhub.py
> +                    "index": false
a description may be too long and trigger a **Lucene’s term byte-length limit of 32766** exception. Why do we need to index this field?
We could improve this mapping using the option [ignore-above](https://www.elastic.co/guide/en/elasticsearch/reference/current/ignore-above.html)

2018-02-23 17:43 UTC, acs approved these changes
LGTM

2018-02-23 17:43 UTC, merged