[ocean] Fix mappings to index Gerrit data
chaoss/grimoirelab-elk pull request #201
Opened 2018-02-12 17:17 UTC by valeriocos

This patch prevents to index possible large text fields returned by the Gerrit API, which may cause failures when uploading the data to ES

2018-02-12 17:39 UTC, acs commented
Hmmm, I won't work in possible causes of failures. But let's talk about it! Thanks!

2018-02-20 10:40 UTC, acs requested changes

2018-02-20 10:40 UTC, acs commented on grimoire_elk/elk/gerrit.py
> +                  "index": false
We want to index this field.

2018-02-22 11:03 UTC, valeriocos commented on grimoire_elk/elk/gerrit.py
> +                  "index": false
Long summaries may trigger a Lucene exception (Lucene’s term byte-length limit of 32766). Why we have to index this field?

2018-02-23 17:44 UTC, acs approved these changes
LGTM

2018-02-23 17:44 UTC, merged