[ocean] Fix mappings to index Meetup data
chaoss/grimoirelab-elk pull request #205
Opened 2018-02-13 08:26 UTC by valeriocos

This patch prevents to index the content of comments and author bios, which may cause failures when uploading the data to ES

2018-02-20 10:47 UTC, acs requested changes

2018-02-20 10:47 UTC, acs commented on grimoire_elk/elk/meetup.py
> -            mapping = """
I won't remove the ES 2.x support because it can cause regressions.

2018-02-23 17:49 UTC, acs reviewed
Hmmm, I can not see ES 2.x support readded.

2018-02-26 09:22 UTC, valeriocos commented
I have just updated the PR

2018-03-02 11:00 UTC, acs approved these changes
LGTM

2018-03-02 11:00 UTC, merged