[ocean] Fix mappings to index NNTP data
chaoss/grimoirelab-elk pull request #207
Opened 2018-02-13 08:44 UTC by valeriocos

This patch prevents to index the subject and the body of NNTP messages which may cause failures when uploading the data to ES

2018-02-20 10:49 UTC, acs requested changes

2018-02-20 10:49 UTC, acs commented on grimoire_elk/elk/nntp.py
> +                    "index": false
we want to index this field

2018-02-22 11:05 UTC, valeriocos commented on grimoire_elk/elk/nntp.py
> +                    "index": false
Long subjects may trigger a Lucene exception (Lucene’s term byte-length limit of 32766). Why we have to index this field?

2018-02-23 17:50 UTC, acs approved these changes
LGTM

2018-02-23 17:50 UTC, merged