[elk] Add areas of code study
chaoss/grimoirelab-elk pull request #228
Opened 2018-02-28 19:10 UTC by alpgarcia

Some new classes added in `ceres_base.py` to ease integration of
cereslib based enrichers.

`sortinghat.py` gelk module was refactored to `sortinghat_gelk.py`
due to importing problems when using `cereslib`, because cereslib
uses `sortinhat` from gelk and, at the same time, gelk was using
`sortinghat` from sortinhat project.

2018-02-28 19:16 UTC, acs commented on grimoire_elk/elk/mappings/git_aoc.json
> +}
Why are we storing the mapping in this directory? We are not following this approach in any other case.

2018-02-28 19:24 UTC, alpgarcia commented on grimoire_elk/elk/mappings/git_aoc.json
> +}
I didn't know where to store it and I don't want to put the explicit mapping in the source file for readability. I just tried to have it closer to the file using it.

The thing is that all enrichers coming from `cereslib` have their own explicit mappings.

2018-03-01 11:12 UTC, sduenas requested changes

2018-03-01 11:12 UTC, sduenas commented on grimoire_elk/elk/ceres_base.py
> +            hit['_source']['metadata__enriched_on'] = dt.utcnow().isoformat()
I would use, `grimoirelab-toolkit` functions to work with dates, but that's only my opinion.

2018-03-01 11:12 UTC, sduenas commented on grimoire_elk/elk/study_ceres_aoc.py
> +#!/usr/bin/python
Change this to use `env`

2018-03-01 17:04 UTC, alpgarcia commented on grimoire_elk/elk/ceres_base.py
> +        self.__in = in_connector
You are right, they should be protected.

2018-03-01 17:05 UTC, alpgarcia commented on grimoire_elk/elk/ceres_base.py
> +        :param in_connector: connector for reading source items from
Do you mean class fields?

2018-03-01 17:19 UTC, sduenas commented on grimoire_elk/elk/ceres_base.py
> +        :param in_connector: connector for reading source items from
Init parameters.

2018-03-01 19:53 UTC, alpgarcia commented
I've addressed all your comments @sduenas. Once you've reviewed them I'll reorganize these commits to have:
- One commit for ceres base.
- One commit for areas of code (refactoring could be include here or in a separated commit).
- One commit for travis setup.
- One commit for updating requirements.

2018-03-05 18:40 UTC, acs commented on grimoire_elk/elk/mappings/git_aoc.json
> +}
It is ok for me then! Let's go ahead with this approach. But at some point we must unify criteria about mappings in gelk and cereslib.

2018-03-05 18:42 UTC, sduenas approved these changes
LGTM

2018-03-05 18:52 UTC, acs approved these changes

2018-03-05 18:52 UTC, acs commented on grimoire_elk/elk/git.py
> +        in_conn = ESPandasConnector(es_conn=es, es_index="git_areas_of_code-raw", sort_on='metadata__timestamp')
Here it is using as Elasticsearch for reading the data from, the same one than the Elasticsearch used for the enriched indexes. In general, these Elasticsearch are different. Is it possible to access the url for the ES with the raw index? Let me check ...  this is how the items are enriched from the raw index. The data for the raw index is passed as a param, so the Enrich object does not have information about where the raw index Elasticsearch is.

```
    def enrich_items(self, ocean_backend, events=False):
        max_items = self.elastic.max_items_bulk
        current = 0
        total = 0
        bulk_json = ""

        items = ocean_backend.fetch()
```

So I will leave as a requisite for this study that the ES is the same for raw and enriched indexes, and if in the future we try to use it in other cases, we need to add support so the Enrich class can obtain in some way where the raw data is.

2018-03-05 19:06 UTC, alpgarcia commented on grimoire_elk/elk/git.py
> +        in_conn = ESPandasConnector(es_conn=es, es_index="git_areas_of_code-raw", sort_on='metadata__timestamp')
Maybe we could open an enhancement issue about `study configuration` and discuss it there as future work.

2018-03-05 19:10 UTC, acs commented on grimoire_elk/elk/git.py
> +        in_conn = ESPandasConnector(es_conn=es, es_index="git_areas_of_code-raw", sort_on='metadata__timestamp')
Yes! My guess is that this config must be passed to the study as params, yes! Good point. Opening a new issue then:

https://github.com/chaoss/grimoirelab-elk/issues/232

2018-03-05 19:10 UTC, merged