Gender
chaoss/grimoirelab-elk pull request #240
Opened 2018-03-08 20:01 UTC by alpgarcia

I did 3 separate commits:
* Add gender info: I followed the most simple approach. If there is gender info coming from sortinghat, add that info to the enriched index. Future work could add a parameter to ignore this information. Current code asumes we want that info if available in sortinghat.
* Add tests for gender methods: basically two test for the methods I've modified. As I see those as a whole, I tested all cases I was aware of and tests started to fail. I decided not to fix the methods in this commit to make clear the errors and the fixes needed (next commit)
* Fix errors mentioned above: this allow to review particular fixes not related with gender info. Imho, they are needed to have a more robust code.

Thanks!

2018-03-09 10:11 UTC, sduenas requested changes

2018-03-09 10:11 UTC, sduenas commented on grimoire_elk/elk/enrich.py
> +            if 'id' in sh_ids:
I would use the `get` method  of `dict` type instead of a set of  `if` blocks. For example:

```
eitem_sh[rol + "_id"] = sh_ids.get('id', None)
```

2018-03-09 10:11 UTC, sduenas commented on tests/test_enrich.py
> +    def test_get_item_sh_fields(self):
I think you should split this method in several tests that will run independently. The idea is to test as much as possible cases at the same time.

2018-03-13 17:22 UTC, alpgarcia commented
I've addressed both comments. I've also changed the code to ensure gender fields are always included in the enriched index and are not empty. `Unknown` and `0` values are used for `author_gender` and `author_gender_acc` instead.

2018-03-13 18:26 UTC, sduenas approved these changes

2018-03-15 06:45 UTC, acs approved these changes
LGTM

2018-03-15 06:45 UTC, merged