[identities] Load identities to sortinghat by bulks
chaoss/grimoirelab-elk pull request #318
Opened 2018-04-13 15:47 UTC by valeriocos

This PR changes the way of loading identities to sortinghat. In a nutshell, instead of loading in memory all the identities before sending them to sortinghat, they are sent to bulks of 500. Thus, the consuption of memory is safe when dealing with a large number of identities. Furthermore, this PR enables also to log exceptions that may occur when processing identities. This log can help to shed some light on mordred
threads that from time to time die without leaving any trace.

2018-04-13 15:58 UTC, sduenas requested changes

2018-04-13 15:58 UTC, sduenas commented on grimoire_elk/elk.py
> +        identities_count += len(new_identities)
This code is exactly the same you wrote above. Don't repeat yourself. Put it inside a method or function.

2018-04-13 17:11 UTC, sduenas approved these changes

2018-04-16 08:25 UTC, acs commented
After talking with @valeriocos there are no performance drawbacks adding the identities by bulks, and it is more robust (you don't need to have all 1 million identities loaded in memory to start doing things) so I merge this PR: Thanks!

2018-04-16 08:25 UTC, merged