[enrich][redmine] Add `assigned_to` fields
chaoss/grimoirelab-elk pull request #381
Opened 2018-06-22 16:29 UTC by alpgarcia

`assigned_to` fields are included after processing the
corresponding identity in SortingHat.

2018-06-22 16:35 UTC, valeriocos approved these changes
LGTM

2018-06-22 16:50 UTC, acs requested changes

2018-06-22 16:50 UTC, acs commented on grimoire_elk/enriched/redmine.py
> +        for rol in self.roles:
I need to review teh code below because it is already included in the shared login for all the enrichers.

2018-06-26 09:20 UTC, acs commented
Reworked in #384

2018-06-26 09:20 UTC, closed without merging