Add code to calculate first response to issue duration
chaoss/grimoirelab-elk pull request #383
Opened 2018-06-24 05:59 UTC by aswanipranjal

closes chaoss/wg-gmd#8

This PR adds the functionality to calculate the first response to issue duration for an issue/pr by someone other than the user who created the issue/pr and adds it to the enriched index for github data source.

2018-06-24 08:49 UTC, valeriocos approved these changes
Thank you @aswanipranjal for the PR. 
LGTM. I added just some minor comments. I involve also @acs in the review

2018-06-24 08:49 UTC, valeriocos commented on grimoire_elk/enriched/github.py
> +        if issue['comments'] + issue['reactions']['total_count'] == 0:
I would convert the if-then-else block to an if-then one, moving out `rich_issue['time_to_first_reaction'] = None` and changing the condition accordingly

2018-06-24 08:49 UTC, valeriocos commented on grimoire_elk/enriched/github.py
> +        """
Please join lines 254 and 255 as it is done here: https://github.com/chaoss/grimoirelab-perceval/blob/master/perceval/backends/core/discourse.py#L124

2018-06-25 07:29 UTC, acs requested changes

2018-06-25 07:29 UTC, acs commented on grimoire_elk/enriched/github.py
> +        """Get the first date at which a comment or reaction was made to the issue by someone
I would use better `get_time_to_first_attention`. In general we are using attention and not reaction, so it is better to use the same semantic in all places.

2018-06-26 13:28 UTC, aswanipranjal commented
@valeriocos @acs I've made the required changes.

2018-06-27 05:18 UTC, acs approved these changes

2018-06-27 05:18 UTC, merged

2018-06-27 05:19 UTC, acs commented
Nice wotk @aswanipranjal