[enriched] Add code to calculate github pull requests enriched data
chaoss/grimoirelab-elk pull request #401
Opened 2018-07-11 07:11 UTC by aswanipranjal

Added code to calculate
- Enriched PR data
- The following GMD code development metrics:
  - forks
  - code merge duration
  - number of review comments
  - Maintainer Response to Merge Request Duration

closes #394

2018-07-11 10:33 UTC, aswanipranjal commented
@acs, @valeriocos, @jgbarah Please review?

2018-07-11 13:22 UTC, valeriocos approved these changes
LGTM. @acs if you agree, we can merge this PR

2018-07-11 16:32 UTC, acs requested changes

2018-07-11 16:32 UTC, acs commented on grimoire_elk/enriched/github.py
> +        if user is not None and user:
All the participants data must come from SH directly, We must not add it here unless we need data that is not included in SH.

2018-07-12 06:43 UTC, acs commented on grimoire_elk/enriched/github.py
> +        if user is not None and user:
No, in both cases we need to generate the identities information from SH, like we do in the rest of enrichers. At least, the information that it is included in SH. Using the git enriched, this is done using:

* Roles to be included: https://github.com/chaoss/grimoirelab-elk/blob/master/grimoire_elk/enriched/git.py#L87
* Addition of identities information: https://github.com/chaoss/grimoirelab-elk/blob/master/grimoire_elk/enriched/git.py#L415

I need to take a look to fix how identities are filled in github enricher for issues. If you want to play with this idea and reach a PR; I will be happy to review it.

2018-07-12 07:14 UTC, aswanipranjal commented on grimoire_elk/enriched/github.py
> +        if user is not None and user:
Okay, I'll try to understand better how identities are being added in the github enricher and make a PR.

Can we merge this for now, then? Because I'd also like to add the fields for the GMD code development metrics which are dependent on github pull request enrich data.

2018-07-12 09:20 UTC, acs commented on grimoire_elk/enriched/github.py
> +        if user is not None and user:
Yes, I think so. If it is following what is done in github issues enricher. once we fix the current one, we can fix the new one.

2018-07-12 09:20 UTC, acs approved these changes

2018-07-12 09:21 UTC, merged