[gitlab] Add milestone attribute to enriched items
chaoss/grimoirelab-elk pull request #445
Opened 2018-10-04 13:08 UTC by valeriocos

This code adds milestone information to enriched items coming from gitlab issues and merge requests. Milestone data is stored in the attribute `milestone`, in case no milestone is present, the value is set to `no-milestone`. Tests have been modified accordingly.

2018-10-04 15:35 UTC, sduenas requested changes
Just minor comments about the code. Please check them.

2018-10-04 15:35 UTC, sduenas commented on grimoire_elk/enriched/gitlab.py
> +NO_MILESTON_TAG = "no-milestone"
Not sure if this is the right value for these cases. What about something like `-empty-`, `-none-` or
`-unassigned-`? We should have a common criteria for these kind of cases.

2018-10-04 15:35 UTC, sduenas commented on tests/test_gitlab.py
>  class TestGit(TestBaseBackend):
Git test?

2018-10-04 15:43 UTC, valeriocos commented on grimoire_elk/enriched/gitlab.py
> +NO_MILESTON_TAG = "no-milestone"
I'm not sure we should have a common value. Feel free to propose the no_milestone_tag. I'll update the PR with the new value

2018-10-04 15:46 UTC, valeriocos commented on tests/test_gitlab.py
>  class TestGit(TestBaseBackend):
It was there before and I didn't modify it. Anyway, I have just refreshed the PR to fix the typo

2018-10-04 16:54 UTC, valeriocos commented on grimoire_elk/enriched/gitlab.py
> +NO_MILESTON_TAG = "no-milestone"
done!

2018-10-04 17:47 UTC, sduenas requested changes
Minor typo you have to fix before merging this patch.

2018-10-04 17:47 UTC, sduenas commented on grimoire_elk/enriched/gitlab.py
> +NO_MILESTON_TAG = "-empty-"
There's a typo. It should be MILESTONE.

2018-10-04 17:52 UTC, valeriocos commented on grimoire_elk/enriched/gitlab.py
> +NO_MILESTON_TAG = "-empty-"
done

2018-10-05 05:42 UTC, sduenas approved these changes

2018-10-05 07:39 UTC, merged