[gitlab] Add csv for gitlab merges and issues
chaoss/grimoirelab-elk pull request #446
Opened 2018-10-04 13:12 UTC by valeriocos

This code includes the CSV files for gitlab merges and issues. The description has been taken from the current indexes deployed in production.

2018-10-05 12:09 UTC, sduenas requested changes
I miss some fields on the CSV.

2018-10-05 12:09 UTC, sduenas commented on schema/gitlab_merges.csv
> +merge_author_login,keyword
I miss `merge_author_domain`,`merge_author_location`, `merge_author_org`.

2018-10-08 07:16 UTC, valeriocos commented
We discussed that the right format for CSVs is the one available for git (https://github.com/chaoss/grimoirelab-elk/blob/master/schema/git.csv), but your comments seem to overlook it. Should I address your comments or modify the full CSV to make it conform to the correct format?

2018-10-08 09:19 UTC, sduenas commented
> Should I address your comments or modify the full CSV to make it conform to the correct format?

Yes, you should. Let's add those fields and we can merge this PR.

2018-10-09 06:12 UTC, sduenas approved these changes
LGTM

2018-10-09 06:13 UTC, merged