[gitlab-enrich] Add onion study
chaoss/grimoirelab-elk pull request #447
Opened 2018-10-04 14:30 UTC by valeriocos

This PR adds the onion study for the GitLab enricher. You can execute the study by including in the cfg of mordred the following lines:
```
[gitlab:merge]
raw_index = test_gitlab-merge-raw
enriched_index = test_gitlab-merge
api-token = ZAxX9AbUdV4HXkpyiuHV
no-archive = true
category = merge_request
sleep-for-rate = true
studies = [enrich_onion:gitlab]

[enrich_onion:gitlab]
in_index_iss = test_gitlab-issue
in_index_prs = test_gitlab-merge
out_index_iss = gitlab_issues_onion
out_index_prs = gitlab_merges_onion
data_source_iss = gitlab-issues
data_source_prs = gitlab-merges
```

2018-10-04 17:43 UTC, sduenas commented
I found an error testing it with the same configuration you put above. I've run it using the next parameters with micro mordred:

```
--enrich --cfg ./setup.cfg --backends gitlab:merge
```

I found weird that it's using `test_gitlab-issue` as index when I'm analyzing merge requests. (I didn't run the enrich with gilab:issue before).

```
[2018-10-04 19:32:03,031 - elasticsearch - DEBUG] - < {"acknowledged":true,"shards_acknowledged":true,"index":"gitlab_issues_onion"}
[2018-10-04 19:32:03,040 - urllib3.connectionpool - DEBUG] - https://localhost:9200 "GET /gitlab_issues_onion/_search HTTP/1.1" 200 176
[2018-10-04 19:32:03,041 - elasticsearch - INFO] - GET https://localhost:9200/gitlab_issues_onion/_search [status:200 request:0.009s]
[2018-10-04 19:32:03,041 - elasticsearch - DEBUG] - > {"aggs":{"max_date":{"max":{"field":"metadata__timestamp"}}},"from":0,"size":0}
[2018-10-04 19:32:03,041 - elasticsearch - DEBUG] - < {"took":5,"timed_out":false,"_shards":{"total":5,"successful":5,"skipped":0,"failed":0},"hits":{"total":0,"max_score":0.0,"hits":[]},"aggregations":{"max_date":{"value":null}}}
[2018-10-04 19:32:03,041 - grimoire_elk.enriched.ceres_base - DEBUG] - No data for metadata__timestamp field found in gitlab_issues_onion index
[2018-10-04 19:32:03,041 - grimoire_elk.enriched.ceres_base - INFO] - Reading items since the beginning of times
[2018-10-04 19:32:03,057 - urllib3.connectionpool - DEBUG] - https://localhost:9200 "GET /test_gitlab-issue/_search HTTP/1.1" 404 391
[2018-10-04 19:32:03,057 - elasticsearch - WARNING] - GET https://localhost:9200/test_gitlab-issue/_search [status:404 request:0.015s]
[2018-10-04 19:32:03,057 - elasticsearch - DEBUG] - > {"aggs":{"timeframe":{"date_histogram":{"field":"grimoire_creation_date","interval":"quarter","min_doc_count":1}}},"from":0,"size":0}
[2018-10-04 19:32:03,057 - elasticsearch - DEBUG] - < {"error":{"root_cause":[{"type":"index_not_found_exception","reason":"no such index","resource.type":"index_or_alias","resource.id":"test_gitlab-issue","index_uuid":"_na_","index":"test_gitlab-issue"}],"type":"index_not_found_exception","reason":"no such index","resource.type":"index_or_alias","resource.id":"test_gitlab-issue","index_uuid":"_na_","index":"test_gitlab-issue"},"status":404}
[2018-10-04 19:32:03,057 - grimoire_elk.elk - ERROR] - Problem executing study enrich_onion:gitlab, NotFoundError(404, 'index_not_found_exception', 'no such index')
```

2018-10-04 17:53 UTC, valeriocos commented
do you have the raw indexes of gitlab your ES instance?

2018-10-05 05:57 UTC, sduenas commented
Then, we will have the same problems after running it with issues if we haven't created the index for MR and we won't have it because it will return this error.

2018-10-05 06:11 UTC, valeriocos commented
Please, check if this also occurs for github issues and pull requests. If this is the case, there is a bug in the onion study, which should be fixed by another PR.

2018-10-05 06:56 UTC, sduenas commented
It's not really a bug in `github` because remember that issues/prs are stored in the same index. So the index always exist before running any of the studies.

2018-10-05 14:06 UTC, valeriocos commented
I have just updated the PR (and the description). @sduenas please review it

2018-10-08 09:38 UTC, alpgarcia commented
I'd say we need `data_source` to be mandatory with no default value. The reason is we need to make a distinction between issues and merge requests results for two reasons:
1. They are computed separately, so if we group results by data source and we use `gitlab` for both, we would be aggregating results, and that numbers would be incorrect. To get the right numbers we should compute all data together, in other case we are mixing results from two different analysis. E.g. we would show core group for MRs and core group for issues as a single group, that is not the same as computing core group for issues and merge requests together.
2. Issues and Merge Requests are different things, so we need to compute and visualize them separately.

2018-10-09 06:31 UTC, sduenas requested changes
I've been testing it and I got the next error:
```
[2018-10-09 08:28:36,056 - grimoire_elk.elk - ERROR] - Problem executing study enrich_onion:gitlab-merge, enrich_onion() missing 1 required positional argument: 'data_source'
Traceback (most recent call last):
  File "/home/sduenas/devel/grimoirelab/sirmordred/utils/micro.py", line 194, in <module>
    args.panels)
  File "/home/sduenas/devel/grimoirelab/sirmordred/utils/micro.py", line 62, in micro_mordred
    get_enrich(config, backend)
  File "/home/sduenas/devel/grimoirelab/sirmordred/utils/micro.py", line 112, in get_enrich
    task.execute()
  File "/home/sduenas/devel/grimoirelab/sirmordred/sirmordred/task_enrich.py", line 308, in execute
    raise e
  File "/home/sduenas/devel/grimoirelab/sirmordred/sirmordred/task_enrich.py", line 306, in execute
    self.__studies()
  File "/home/sduenas/devel/grimoirelab/sirmordred/sirmordred/task_enrich.py", line 267, in __studies
    do_studies(ocean_backend, enrich_backend, studies_args)
  File "/home/sduenas/devel/grimoirelab/elk/grimoire_elk/elk.py", line 485, in do_studies
    raise e
  File "/home/sduenas/devel/grimoirelab/elk/grimoire_elk/elk.py", line 482, in do_studies
    study(ocean_backend, enrich_backend, **params)
TypeError: enrich_onion() missing 1 required positional argument: 'data_source'
```

2018-10-09 07:07 UTC, valeriocos commented
did you add to the study section the param 'data_source'?

2018-10-09 07:48 UTC, sduenas commented
> did you add to the study section the param 'data_source'?

I forgot to add that, now it works. In any case, I don't see the point to include the datasource when you are running a study which it's name says what the datasource is.

> Furthermore, which same error are you referring?

It was a typo. I meant `next errot` instead of `same error`.

2018-10-09 08:01 UTC, valeriocos commented
I see, but in the current implementation there is no clear way to know the type of `data_source`.

If we take the configuration in the first comment of this PR, you can see that `studies` in the section `gitlab:issue` contains `enrich_onion:gitlab-issue`. The part on the left (`enrich_onion`) is the name of the method that will be executed, while the part on the right ( `gitlab-issue`) is an ID, that can take any value (e.g., gi, xxx, etc.). Thus, by default we cannot rely on the ID to set up the `data_source` value.

2018-10-09 09:18 UTC, sduenas approved these changes
It works to me. I guess the exception raised by this study should be catched by mordred at some poin.

2018-10-09 09:21 UTC, merged

2018-10-09 09:34 UTC, valeriocos commented
It's intercepted here: https://github.com/chaoss/grimoirelab-elk/blob/f5a38c9ce433d14a0e4a84b06e7fdd3f4323f0a0/grimoire_elk/elk.py#L481 and shown in the logs

2018-10-09 09:39 UTC, sduenas commented
But it's raised again.