Update gerrit.csv
chaoss/grimoirelab-elk pull request #452
Opened 2018-10-15 10:34 UTC by lukaszgryglicki

So GitHub can create pretty formatted output.

2018-10-15 11:08 UTC, alpgarcia requested changes

2018-10-15 11:08 UTC, alpgarcia commented on schema/gerrit.csv
> +name,type,bool,description
Please use `aggregatable` instead of `bool` as in [git.csv](https://github.com/chaoss/grimoirelab-elk/blob/master/schema/git.csv)

2018-10-15 11:10 UTC, alpgarcia commented
Thanks so much for the contribution,please consider the change I proposed above.

2018-10-29 12:12 UTC, valeriocos commented
Hi @lukaszgryglicki , did you have time to check @alpgarcia 's comment?

2018-11-16 13:38 UTC, valeriocos commented
@lukaszgryglicki I'm closing this PR, which seems inactive. Feel free to reopen it and address @alpgarcia 's comment

2018-11-16 13:38 UTC, closed without merging