[utils] Avoid enriching items over and over
chaoss/grimoirelab-elk pull request #489
Opened 2018-10-30 15:48 UTC by valeriocos

This code prevents to trigger enrichment operations over all raw items for backends not having neither from_date or offset attributes in their signatures. This is the case of backends like `dockerhub`, `googlehits`, `jenkins`, `rss` and `twitter.

2018-10-30 15:55 UTC, valeriocos commented
@acs could you have a look at this PR? My feeling is that the code could be simplified even more, like this. What do you think?
```
def get_last_enrich(backend_cmd, enrich_backend):
    if backend_cmd:
        backend = backend_cmd.backend
        # Only supported in data retrieved from a perceval backend
        # Always filter by repository to support multi repository indexes
        backend_name = enrich_backend.get_connector_name()
        filter_ = get_repository_filter(backend, backend_name)
        last_enrich = enrich_backend.get_last_update_from_es([filter_])
    else:
        last_enrich = enrich_backend.get_last_update_from_es()

    return last_enrich
```

2018-11-07 09:13 UTC, valeriocos commented
ping @acs

2018-11-07 17:40 UTC, acs approved these changes
LGTM

2018-11-08 13:01 UTC, alpgarcia commented
It seems enrichment is still not incremental. `last_enrich` is not used at all in:
https://github.com/chaoss/grimoirelab-elk/blob/master/grimoire_elk/elk.py#L449

2018-11-08 13:39 UTC, valeriocos commented
ok, I'm going to check it

2018-11-08 21:00 UTC, sduenas requested changes
We have seen that some code is also needed here:
https://github.com/chaoss/grimoirelab-elk/blob/master/grimoire_elk/elk.py#L449

As you can see, there's a doble check about the usage of `from-date`, `offset` or nothing.

2018-11-16 16:55 UTC, alpgarcia commented
LGTM, thanks!

2018-11-16 17:02 UTC, alpgarcia commented
Merged in e1e49a8809187321bf8e540fc2dfed8036d6d611

2018-11-16 17:02 UTC, closed without merging