Documentation added on github_issues.csv
chaoss/grimoirelab-elk pull request #529
Opened 2018-12-17 15:16 UTC by propol

Added the metrics' documentation on the github_issues.csv file in the schema folder. 
This is based to my use of the GrimoireLab tool during my thesis project :)
Also, consulted the other documented schema's to keep the same description style.

2018-12-17 15:31 UTC, propol commented
Sure @alpgarcia , I will do it right now :)

2018-12-19 12:06 UTC, alpgarcia requested changes
Please address my comments. Most of them are minor changes due to typos I found while reading the document.

Thanks a lot!

2018-12-19 12:06 UTC, alpgarcia commented on schema/github_issues.csv
> +project,keyword,true,"The project name."
I'd say just `Project name` as there usually are several projects.

2018-12-19 12:06 UTC, alpgarcia commented on schema/github_issues.csv
> +repository,keyword,true,"The repository's name."
As in the case of Project, I would say just `Repository name`

2018-12-19 12:34 UTC, propol commented on schema/github_issues.csv
> +author_bot,boolean,true,"True/False if the autho is a bot or not."
Done!

2018-12-19 12:34 UTC, propol commented on schema/github_issues.csv
> +metadata__gelk_version,keyword,true,"Version of the backed used to enrich the data."
Done

2018-12-19 12:34 UTC, propol commented on schema/github_issues.csv
> +metadata__timestamp,date,true,"Date when the item was stored in the ElasticSearch db as a raw index."
Done

2018-12-19 12:35 UTC, propol commented on schema/github_issues.csv
> +project,keyword,true,"The project name."
Done

2018-12-19 12:35 UTC, propol commented on schema/github_issues.csv
> +repository,keyword,true,"The repository's name."
Done :)

2018-12-20 10:43 UTC, alpgarcia commented
Thanks a lot for your contribution!

2018-12-20 10:43 UTC, merged