[ELK] Update license info
chaoss/grimoirelab-elk pull request #548
Opened 2019-02-18 13:19 UTC by valeriocos

This code updates license information for every source code file in ELK.

2019-02-19 11:25 UTC, canasdiaz requested changes
Some minor changes requested to make sure we don't break the aim of the commits according to the git log message, which is update the license info.

2019-02-19 11:25 UTC, sanacl commented on utils/e2k.py
> +    """Enriched to Kibana Publisher"""
This comment should not be part of the commit.

2019-02-19 11:25 UTC, sanacl commented on utils/gelk.py
> +    """Gelk: perceval2ocean and ocean2kibana"""
This comment should not be part of the comment

2019-02-19 11:25 UTC, sanacl commented on utils/gelk_mapping.py
> +    """Tool to show the mapping used in a GrimoireELK data source"""
This comment should not be part of the commit.

2019-02-19 11:25 UTC, sanacl commented on utils/get_git_repos.py
> +    """GitHub repository listing for an org"""
This comment should not be part of the commit.

2019-02-19 11:25 UTC, sanacl commented on utils/gh2arthur.py
> +    """GitHub to Kibana"""
This comment should not be part of the commit.

2019-02-19 11:25 UTC, sanacl commented on utils/gh2k.py
> +    """GitHub to Kibana"""
This comment should not be part of the commit.

2019-02-19 11:25 UTC, sanacl commented on utils/index_mapping.py
> +    """Tool to ensure correct mappings in GrimoireLab indexes"""
This comment should not be part of the commit.

2019-02-19 11:25 UTC, sanacl commented on utils/p2o.py
> +    """Perceval2Ocean tool"""
This comment should not be part of the commit.

2019-02-20 11:28 UTC, canasdiaz approved these changes

2019-02-20 12:09 UTC, merged