[elastic] Add method `delete_raw_items`
chaoss/grimoirelab-elk pull request #570
Opened 2019-03-05 17:33 UTC by valeriocos

This PR includes the method to delete items from the raw index before a given date. This change is needed to define retention policy data.

2019-03-06 16:07 UTC, sduenas requested changes
Please check my comments.

2019-03-07 12:27 UTC, valeriocos commented on grimoire_elk/utils.py
> +    analyzers = None
Because the get_elastic doesn't have a backend, thus the code doesn't enter here: https://github.com/chaoss/grimoirelab-elk/blob/d4a8e7771b12527efb5267b6a67a77393335dd05/grimoire_elk/utils.py#L241 and doesn't init the variable `analyzers`

2019-03-07 22:22 UTC, sduenas reviewed
Please check my comment below. I tested the PR and it works fine.

2019-03-07 22:22 UTC, sduenas commented on grimoire_elk/elastic.py
> +        if not hours_to_retain:
We can consider this like a bug or not. If you set `hours_to_retain` to `0` nothing will be deleted. I'm ok with it but this means the log message below never will show up when is set to `0`.

2019-03-08 17:48 UTC, sduenas approved these changes
LGTM

2019-03-08 17:48 UTC, merged