[enriched-github2] New enricher to handle github comments
chaoss/grimoirelab-elk pull request #737
Opened 2019-11-19 18:56 UTC by valeriocos

This code proposes a new github enricher to handle github comments. The old enricher is left in place to avoid breaking changes with customer dashboards.

The new enricher is added to the list of connectors, it can be defined in the mordred setup.cfg as follows:
```
[github2]
api-token = ...
raw_index = github_chaoss_raw
enriched_index = github_chaoss_enriched
sleep-for-rate = true

[github2:prs]
api-token = ...
raw_index = github-prs_chaoss_raw
enriched_index = github-prs_chaoss_enriched
sleep-for-rate = true
category = pull_request
no-archive = true
```

Similar names must be present in the projects.json

Note that since this is PR is a WIP, tests and schema haven't been provided yet.

2019-11-21 10:57 UTC, alpgarcia requested changes
I've been reviewing Sigils panels and the new indexes seem to have at least the same info we had before (except painless fields that are created at index pattern level). 

I suggest the following changes:
* I'd modify the code to get fields `is_github_*` `is_github2_*` for future compatibility. Imho these fields should not depend on the enricher because if we use them in the dashboards we would need to modify them if the enricher name changes.
* `issue_id_in_repo` should probably in issues too. I'd say all `issue_*` fields should be always present to allow to filtering regardless item type. Same for Pull Requests equivalent fields.
* I wonder whether having `issue_closed_at` could be useful for some metric regarding comments. For instance number of comments of issues closed at a give date...
* I see no reactions information for issues/PRs, only for comments, but I can react to them.

2019-11-22 15:53 UTC, valeriocos commented
Comments addressed @alpgarcia , please check

2019-11-26 11:50 UTC, alpgarcia requested changes
One last change. Reactions object should be flatten for consistency's sake. Now it is stored as follows:
```
"reactions": {
            "properties": {
              "+1": {
                "type": "long"
              },
              "-1": {
                "type": "long"
              },
              "confused": {
                "type": "long"
              },
              "eyes": {
                "type": "long"
              },
              "heart": {
                "type": "long"
              },
              "hooray": {
                "type": "long"
              },
              "laugh": {
                "type": "long"
              },
              "rocket": {
                "type": "long"
              },
              "total_count": {
                "type": "long"
              }
            }
},
```

2019-11-27 16:24 UTC, alpgarcia approved these changes

2019-11-27 16:24 UTC, merged