[enriched/bugzilla] Add new field `whiteboard`
chaoss/grimoirelab-elk pull request #938
Opened 2020-09-24 13:32 UTC by zhquan

This code adds a new field to the enriched index that gives us
information about `whiteboard`.

Signed-off-by: Quan Zhou <quan@bitergia.com>

2020-09-24 16:27 UTC, sduenas requested changes
The PR looks ok but you need to update the CVS file with this information. I also think we should also add the same field for `bugzillarest` so we can have similar indices.

2020-09-25 12:44 UTC, sduenas commented on grimoire_elk/enriched/bugzillarest.py
> +        if issue['whiteboard'] != "":
Is this field in the item always? Not sure if that's going to create a `KeyError`.

2020-09-25 14:23 UTC, zhquan commented on grimoire_elk/enriched/bugzillarest.py
> +        if issue['whiteboard'] != "":
In Bugzillarest the field is always there but not in Bugzilla. So to have the same behavior:

Option 1:
- Bugzilla: Add the field `whiteboard` only when the field does exist on the raw index.
- Bugzillarest: Add the field `whiteboard` only when the field is not empty("") on the raw index

Option 2:
- Bugzilla: Add the field `whiteboard` always and when the field doesn't exist set as empty("").
- Bugzillarest: Add the field `whiteboard` always

I choose the option 1

2020-09-25 14:28 UTC, sduenas approved these changes
LGTM

2020-09-28 09:22 UTC, merged