[weblate] New enricher to handle changes
chaoss/grimoirelab-elk pull request #940
Opened 2020-10-06 17:39 UTC by zhquan

This code proposes a new weblate enricher to handle changes
including thier units and authors information.

The new enricher is added to the list of connetors and can be
defined in the mordred setup.cfg as follows:
´´´
[weblate]
raw_index = weblate_chaoss_raw
enriched_index = weblate_chaoss_enriched
api-token= ...
no-archive = true
sleep-for-rate = true
´´´

projects.json
```
{
  "chaoss": {
    "weblate": [
      "my.weblate.org"
    ]
  }
}
```

Tests added accordingly.

Signed-off-by: Quan Zhou <quan@bitergia.com>

2020-10-08 19:22 UTC, mafesan requested changes
@zhquan Overall it LGTM, but please check my comments. Thank you!

2020-10-08 19:22 UTC, mafesan commented on grimoire_elk/enriched/weblate.py
> +                eitem['unit_' + data] = user_data[data]
I think there are some boolean fields here (`has_comment`, `has_failing_check` and `has_suggestion`) which could be converted to 0/1 values as we do in other similar fields from other enrichers.

Example:
https://github.com/chaoss/grimoirelab-elk/blob/cfbac57c84df8367fa4c914eb17b95e78686f99b/grimoire_elk/enriched/git.py#L375 

The reason for this conversion is to ease the aggregation of these fields. For instance, to have the number of translations (units) with comments per author, we would make a `sum` aggregation of the `has_comment` field.

2020-10-08 19:22 UTC, mafesan commented on grimoire_elk/enriched/weblate.py
> +                eitem['unit_' + data] = user_data[data]
The fields `unit_content_hash` and `unit_id_hash` are of type `number` and they should be of type `string` according to Weblate doc (https://docs.weblate.org/en/latest/api.html#get--api-units-(int-id)-), please check how these fields are handled (maybe is something to fix from the Perceval backend).

2020-10-08 19:22 UTC, mafesan commented on grimoire_elk/raw/weblate.py
> +        :returns:        dictionary with a key, 'items', with the mapping
Minor comment: please remove the extra spaces.

2020-10-08 20:53 UTC, zhquan commented on grimoire_elk/enriched/weblate.py
> +                eitem['unit_' + data] = user_data[data]
But the API returns as `number` instead of `string` see https://translations.documentfoundation.org/api/units/24794381/

2020-10-09 07:20 UTC, mafesan commented on grimoire_elk/enriched/weblate.py
> +                eitem['unit_' + data] = user_data[data]
Ok, thank you for checking it

2020-10-11 09:40 UTC, sduenas requested changes
Just a minor comment. Update the weblate repository links.

2020-10-11 09:40 UTC, sduenas commented on requirements.txt
> +-e git+https://github.com/Bitergia/grimoirelab-perceval-weblate/#egg=grimoirelab-perceval-weblate
This backend was moved to `chaoss`. Can you update the link?

2020-10-11 10:17 UTC, sduenas commented on requirements.txt
> +-e git+https://github.com/Bitergia/grimoirelab-perceval-weblate/#egg=grimoirelab-perceval-weblate
Can you also rebase the PR?

2020-10-13 09:27 UTC, merged

2020-10-13 09:28 UTC, sduenas reviewed
LGTM