Add twitter schema file #936
chaoss/grimoirelab-elk pull request #965
Opened 2021-03-18 10:39 UTC by VSevagen

Signed-off-by: sevagenv <sevagenv@gmail.com>

This is a PR for issue #936. It is my very first PR so there might be a few issues with it. Looking forward to get it reviewed.

2021-03-22 10:06 UTC, sduenas requested changes
Thanks for the PR. Would you mind to check #964? There's some fields that are deprecated and shouldn't be part of the schema.

Also, the commit message should be:

```
[schema] Add twitter schema file

Twitter schema was missing. This commit serves to add it.

Signed-off-by: sevagenv <sevagenv@gmail.com>
```

2021-03-22 13:43 UTC, sduenas requested changes
The PR looks ok. Although there are minor changes you need to address before merging it.

2021-03-22 13:43 UTC, sduenas commented on schema/twitter.csv
> +is_twitter_twitter,long,true,N\A
This field is `is_twitter_tweet`, it's used to count number of tweets in complex agregations.

2021-03-22 13:43 UTC, sduenas commented on schema/twitter.csv
> +project,keyword,true,"Project."
Project name.

2021-03-22 13:43 UTC, sduenas commented on schema/twitter.csv
> +tag,keyword,true,"The text of the Hashtag."
`tag` is the tag set by perceval when retrieving the item.

2021-03-22 15:05 UTC, sduenas commented on schema/twitter.csv
> +is_twitter_twitter,long,true,"Count number of tweets in complex aggregations."
I think the name of the field is `is_twitter_tweet`, am I wrong?

2021-03-22 15:08 UTC, VSevagen commented on schema/twitter.csv
> +is_twitter_twitter,long,true,"Count number of tweets in complex aggregations."
I'm not sure. I'll check once

2021-03-22 15:18 UTC, VSevagen commented on schema/twitter.csv
> +is_twitter_twitter,long,true,"Count number of tweets in complex aggregations."
In the twitter index pattern, its listed as `is_twitter_twitter`.

2021-03-23 10:25 UTC, sduenas commented on schema/twitter.csv
> +is_twitter_twitter,long,true,"Count number of tweets in complex aggregations."
The index patter is wrong too. The real field is `is_twitter_tweet`. This is from a real example.
![imagen](https://user-images.githubusercontent.com/833352/112131926-5aebf580-8bca-11eb-8524-db545e6ffbcd.png)

I suggest to change it to the name of this field and to update the index pattern too. Do you mind to change it too? It's in `grimoirelab-sigils` repository.

2021-03-23 10:58 UTC, VSevagen commented on schema/twitter.csv
> +is_twitter_twitter,long,true,"Count number of tweets in complex aggregations."
Alright. I'll change it. I'll create another PR for updating the index pattern.

2021-03-23 14:55 UTC, sduenas approved these changes
LGTM

2021-03-23 15:06 UTC, merged