[pyproject] Update packages and python to "^3.6.1"
chaoss/grimoirelab-elk pull request #994
Opened 2021-08-06 10:43 UTC by zhquan

python = "^3.6.1"
requests = "2.26.0"
urllib3 = "1.26.5"
perceval-weblate = {branch = "master", git = "https://github.com/Bitergia/grimoirelab-perceval-weblate"}

poetry.lock updated accordingly.

Signed-off-by: Quan Zhou <quan@bitergia.com>

2021-08-16 10:24 UTC, vchrombie requested changes
Thanks, @zhquan.
Looks good but had a small suggestion.

2021-08-16 10:24 UTC, vchrombie commented on pyproject.toml
> +perceval-weblate = {branch = "master", git = "https://github.com/Bitergia/grimoirelab-perceval-weblate"}
I think the repository is moved to the CHAOSS organization. I think we can update the URL.

```suggestion
perceval-weblate = {branch = "master", git = "https://github.com/chaoss/grimoirelab-perceval-weblate"}
```

2021-08-23 09:24 UTC, vchrombie approved these changes
LGTM

2021-08-23 09:29 UTC, sduenas approved these changes
LGTM

2021-08-23 09:35 UTC, merged