[gitlab] Autodetect gitlab enterprise-url arg
chaoss/grimoirelab-elk pull request #995
Opened 2021-08-09 18:46 UTC by Alch-Emi

The `enterprise-url` parameter of the `gitlab` backend is currently left to be specified by the user in the config file.  This commit removes this burden from the user by automatically detecting the enterprise URL from the url passed to get_perceval_params_from_url()`.

This aims to make it easier for users to work with enterprise GitLab instances by removing the need to use the `enterprise-url` at all.

As far as I know, this does not introduce any backwards-compatibility issues.

2021-08-10 09:41 UTC, sduenas requested changes
Please check my comments. The patch looks ok, though. Thanks for the contribution.

2021-08-10 09:41 UTC, sduenas commented on grimoire_elk/raw/gitlab.py
> +        backend = '/'.join(repo.split('/')[:-2])
I would add a comment to explain that this is done to remove the owner and the repository from the repo url. It's a bit confusing, in my opinion, for someone like me that's reading the code for the first time.

2021-08-10 09:41 UTC, sduenas commented on grimoire_elk/raw/gitlab.py
> +        if backend != 'https://gitlab.com':
I would rename `backend` to `host`. I makes more clear what the variable contains. We usually use backend with other meaning.

2021-08-11 23:24 UTC, Alch-Emi commented on grimoire_elk/raw/gitlab.py
> +        backend = '/'.join(repo.split('/')[:-2])
Sounds good!

2021-08-12 08:08 UTC, sduenas approved these changes
LGTM

2021-08-12 08:34 UTC, merged